### ISSUE TITLE
XSS issues

### ISSUE THREAD

**Issue by unlimitedcoder2** [JeroenoBoy/Insult.tech#1]
`https://insult.tech/";alert(1);a="`

**Comment by unlimitedcoder2** [comment]
you also pushed node_modules lol

**Comment by DebitCardz** [comment]
These are major issues that need to be patched right away.

**Comment by JeroenoBoy** [comment]
> `https://insult.tech/";alert(1);a="`

Yes I'm already aware of this but can't fix it rn

**Comment by JeroenoBoy** [comment]
> you also pushed node_modules lol

Since its just node-fetch I don't realy care

**Comment by DebitCardz** [comment]
> > you also pushed node_modules lol
> 
> Since its just node-fetch I don't realy care

really*

**Comment by unlimitedcoder2** [comment]
![img](https://sharethe.minecraftdoublesmoothstoneslab.website/i/lc70.png)
@JeroenoBoy is silencing people
we need free speech on this repo
